type class1 = class {
    var v1: int;
    
    func __plus(other: class1): int
        return v1 + other->v1;
    end __plus

    func __times(other: class1): int
        return v1 * other->v1;
    end __times

    func __minus(other: class1): int
        return v1 - other->v1;
    end __minus

    func __div(other: class1): int
        return v1 / other->v1;
    end __div

    func __equal(other: class1): bool
        return v1 == other->v1;
    end __equal

    func __nequal(other: class1): bool
        return v1 != other->v1;
    end __nequal

    func __less(other: class1): bool
        return v1 < other->v1;
    end __less

    func __greater(other: class1): bool
        return v1 > other->v1;
    end __greater

    func __greaterEqual(other: class1): bool
        return v1 >= other->v1;
    end __greaterEqual

    func __lessEqual(other: class1): bool
        return v1 <= other->v1;
    end __lessEqual
};

var obj1: class1;
var obj2: class1;
var res: int;
var res2: bool;

allocate obj2;
allocate obj1;

obj1->v1 = 3;
obj2->v1 = 109;

res = obj1 + obj2;
write res;

res = obj1 * obj2;
write res;

res = obj2 - obj1;
write res;

res = obj2 / obj1;
write res;

res2 = obj1 == obj2;
write res2;

res2 = obj1 != obj2;
write res2;

res2 = obj1 < obj2;
write res2;

res2 = obj1 > obj2;
write res2;

res2 = obj1 >= obj2;
write res2;

res2 = obj1 <= obj2;
write res2;

